Bebederos/urls.py
from django.conf.urls import url, include
from django.contrib import admin

#urls of the apps
from accounts import urls as accountsUrls
from visitas import urls as visitasUrls
from construccion import urls as construccionUrls
from pruebasAgua import urls as pruebasAguaUrls
from incidencias import urls as incidenciasUrls
from mantenimiento import urls as mantenimientoUrls
from bebederos import urls as bebederosUrls
from plantillas import urls as plantillasUrls

#Media and static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^admin/', admin.site.urls),
    url(r'^', include(visitasUrls, namespace="visitas")),
    url(r'^', include(construccionUrls, namespace="construccion")),
    url(r'^', include(pruebasAguaUrls, namespace="pruebas")),
    url(r'^', include(incidenciasUrls, namespace="incidencias")),
    url(r'^', include(mantenimientoUrls, namespace="mantenimiento")),
    url(r'^', include(bebederosUrls, namespace="bebederos")),
    url(r'^', include(plantillasUrls, namespace="plantillas")),    
    url(r'^', include(accountsUrls, namespace="accounts")),
]

#Media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Static
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
	url(r'^login/$', login,name="login"),
	url(r'^logout/$', logout, name="logout"),
	url(r'^accounts/profile/$', views.ViewProfile.as_view(), name="ViewProfile"),
#	url(r'^accounts/nuevo/$', views.CreateViewAccount.as_view(), name="CreateViewAccount"),	
#	url(r'^change-password/$', views.ViewChangePassword.as_view(), name='ViewChangePassword'),

#	url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),
#	url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),
#	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),
#	url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),

	url(r'^expediente/export/zip/(?P<pk>\d+)/$', views.ExportExpedienteZIP, name='ExportExpedienteZIP'),
	url(r'^reporte_fotografico/export/zip/(?P<pk>\d+)/$', views.ExportFotosEvidenciaZIP, name='ExportFotosEvidenciaZIP'),
#	url(r'^region/estado/reporte_avance/zona/(?P<pk>[-\w]+)/$', views.ListViewAvanceEscuelas.as_view(), name="ListViewAvanceEscuelasPorZona"),

#	url(r'^region/estado/zona/$', views.ListViewZonas.as_view(), name="ListViewZonas2"),
#	url(r'^escuelas/por_ejecutora/$', views.ListViewEscuelas.as_view(), name="ListViewEscuelasPorEjecutora"),
#	url(r'^region/(?P<numero>[-\w]+)/estados/$', views.ListViewEntidades.as_view(), name="ListViewEntidades"),
	url(r'^escuelas/avance/export/csv/(?P<pk>\d+)/$', views.ExportAvancePorEscuelasCSV, name='ExportAvancePorEscuelasCSV'),
	url(r'^escuelas/search/$',views.SearchViewEscuelas.as_view(), name='SearchViewEscuelas'),
	url(r'^escuela/(?P<username>[-\w]+)/$', views.DetailViewEscuela.as_view(), name="DetailViewEscuela"),
	url(r'^escuela/mapa/(?P<pk>[-\w]+)/$', views.DetailViewMapa.as_view(), name="DetailViewMapa"),
	url(r'^escuela/actualizar/expediente/(?P<pk>[-\w]+)/$', views.UpdateViewEscuelaExpediente.as_view(), name="UpdateViewEscuelaExpediente"),
	url(r'^escuela/actualizar/(?P<username>[-\w]+)/$', views.UpdateViewEscuela.as_view(), name="UpdateViewEscuela"),
	url(r'^municipio/(?P<pk>[-\w]+)/escuela/crear/$', views.CreateViewEscuela.as_view(), name="CreateViewEscuela"),
	url(r'^municipio/(?P<pk>[-\w]+)/$', views.ListViewEscuelas.as_view(), name="ListViewEscuelas"),
	url(r'^estado/reporte_general/(?P<slug>[-\w]+)/$', views.ListViewAvanceEscuelas.as_view(), name="ListViewAvanceEscuelas"),
	url(r'^estado/(?P<slug>[-\w]+)/$', views.ListViewZonas.as_view(), name="ListViewZonas"),
	url(r'^estados/$', views.ListViewEntidades.as_view(), name="ListViewEntidades"),	
	url(r'^region/(?P<numero>[-\w]+)/$', views.ListViewEntidades.as_view(), name="ListViewEntidades"),
	url(r'^regiones/$', views.ListViewRegiones.as_view(), name="ListViewRegiones"),
	url(r'^$', views.ViewHome.as_view(), name="ViewHome"),
    ]

bebederos/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^bebederos/avance/export/csv/(?P<pk>\d+)/$', views.ExportAvanceBebederosCSV, name='ExportAvanceBebederosCSV'),
	url(r'^bebederos/trazabilidad/export/pdf/(?P<pk>\d+)/$', views.ExportComprobanteTrazabilidadPDF, name="ExportComprobanteTrazabilidadPDF"),
	url(r'^bebederos/update/(?P<pk>\d+)/$', views.UpdateViewBebedero.as_view(), name="UpdateViewBebedero"),	
]

incidencias/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^incidencia/(?P<pk>\d+)/$', views.UpdateViewIncidencia.as_view(), name="UpdateViewIncidencia"),
	url(r'^incidencias/(?P<pk>\d+)/$', views.CRViewIncidencias.as_view(), name="CRViewIncidencias"),
	url(r'^incidencias/export/(?P<pk>\d+)/csv/$', views.ExportIncidenciasCSV, name='ExportIncidenciasCSV'),	
	url(r'^incidencias/$', views.CRViewIncidencias.as_view(), name="ListViewIncidencias"),
]

pruebasAgua/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^pruebas/export/csv/(?P<pk>\d+)/$', views.ExportPruebasPorEscuelasCSV, name='ExportPruebasPorEscuelasCSV'),
	url(r'^pruebas/etiquetas/export/zip/(?P<pk>\d+)/$', views.ExportEtiquetasZIP, name='ExportEtiquetasZIP'),
#	url(r'^pruebas/primera/calcula_sp/(?P<pk>\d+)/$', CalculateViewSistemaPotabilizador.as_view(), name="CalculateViewSistemaPotabilizador"),
	url(r'^pruebas/primera/(?P<pk>\d+)/$', views.CRUViewPrimerPrueba.as_view(), name="CRUViewPrimerPrueba"),
	url(r'^pruebas/segunda/(?P<pk>\d+)/$', views.CRUViewSegundaPrueba.as_view(), name="CRUViewSegundaPrueba"),
]

visitas/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	#DescargasZip
	url(r'^cedulas_identificacion/export/zip/(?P<pk>\d+)/$', views.ExportCedulasIdentificacionZIP, name='ExportCedulasIdentificacionZIP'),
	url(r'^planos_conjunto/export/zip/(?P<pk>\d+)/$', views.ExportPlanosConjuntoZIP, name='ExportPlanosConjuntoZIP'),
	url(r'^distribucion_planta/export/zip/(?P<pk>\d+)/$', views.ExportDistribucionesPlantaZIP, name='ExportDistribucionesPlantaZIP'),
	url(r'^memoria_calculo/export/zip/(?P<pk>\d+)/$', views.ExportMemoriasCalculoZIP, name='ExportMemoriasCalculoZIP'),
	url(r'^plano_instalacion_electrica/export/zip/(?P<pk>\d+)/$', views.ExportPlanosInstalacionElectricaZIP, name='ExportPlanosInstalacionElectricaZIP'),
	url(r'^plano_instalacion_hidraulica/export/zip/(?P<pk>\d+)/$', views.ExportPlanosInstalacionHidraculicaZIP, name='ExportPlanosInstalacionHidraculicaZIP'),
	url(r'^plano_instalacion_sanitaria/export/zip/(?P<pk>\d+)/$', views.ExportPlanosInstalacionSanitariaZIP, name='ExportPlanosInstalacionSanitariaZIP'),
	url(r'^inicio_funcionamiento/export/zip/(?P<pk>\d+)/$', views.ExportActasFuncionamietoZIP, name='ExportActasFuncionamietoZIP'),

	url(r'^visita/de_acuerdo/(?P<pk>\d+)/$', views.CRViewVisitaDeAcuerdo.as_view(), name="CRViewVisitaDeAcuerdo"),
	url(r'^visita/entrega/(?P<pk>\d+)/$', views.CRViewInicioFuncionamiento.as_view(), name="CRViewInicioFuncionamiento"),
	url(r'^visita/acta_entrega/(?P<pk>\d+)/$', views.CRViewActaEntrega.as_view(), name="CRViewActaEntrega"),	
]

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View
from .models import *
from visitas.models import *
from construccion.models import *
from pruebasAgua.models import *
from bebederos.models import *
from mantenimiento.models import Mantenimiento
from .forms import *
from bebederos.forms import BebederoCreateForm
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import csv
from datetime import datetime
from oficios.models import *

#Librerias para generar ZIP
import zipfile
import os
from django.http import HttpResponse
from django.conf import settings
from io import BytesIO

#Ver perfil al iniciar sesión
class ViewProfile(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "accounts/profile.html"
		user = User.objects.get(pk=request.user.pk)

		try:
			perfil = Perfil.objects.get(user=user)
			entidad = Entidad.objects.get(coordinador_estatal=user)
		except:
			perfil = None
	
		context = {
			'perfil': perfil,
		}
		return render(request,template_name, context)

#Lista de regiones
class ListViewRegiones(View):
	@method_decorator(login_required)
	def get(self, request):
		template_name = "accounts/listRegiones.html"	
		user = User.objects.get(pk=request.user.pk)
		perfil = Perfil.objects.get(user=user)

		regiones = Region.objects.all()

		context = {
			'regiones': regiones,
		}
		return render(request,template_name, context)

#Lista de entidades
class ListViewEntidades(View):
	@method_decorator(login_required)
	def get(self, request, numero=None):
		template_name = "accounts/listEntidades.html"
		
		if request.user.perfil.cargo == "SIM":
			region = None
			sim = User.objects.get(pk=request.user.pk)
			entidades = Entidad.objects.filter(sim=sim).order_by("partida")
		elif request.user.perfil.tipo == "Laboratorio":
			region = None
			laboratorio = User.objects.get(pk=request.user.pk)
			entidades = Entidad.objects.filter(laboratorio=laboratorio)
		elif request.user.perfil.tipo == "PQ" or request.user.perfil.tipo == "Administrador" or request.user.perfil.tipo == "PM" or request.user.perfil.tipo == "INIFED"  or  request.user.perfil.tipo == "Invitado":
			region = Region.objects.get(numero=numero)
			entidades = Entidad.objects.filter(region=region).order_by("partida")

		context = {
			'region': region,
			'entidades': entidades,
		}
		return render(request,template_name, context)

#Lista de zonas
class ListViewZonas(View):
	@method_decorator(login_required)
	def get(self, request, slug):
		template_name = "accounts/listZonas.html"
		entidad = Entidad.objects.get(slug=slug)
		entidad.CountEscuelas()
		zonas = Zona.objects.filter(entidad=entidad)
		municipios = Municipio.objects.filter(zona__in=zonas)
		region = Region.objects.get(entidad=entidad)
		oficios = Oficio.objects.filter(entidad=entidad)
#		print(oficios)

#		EdicionEntidadForm = EntidadUpdateForm(instance=entidad)

		ListMunicipiosPorZona = []
		for zona in zonas:
			ListMunicipiosPorZona.append({'zona': zona, 'municipios': Municipio.objects.filter(zona=zona)})
		
		context = {
			'entidad': entidad,
			'ListMunicipiosPorZona': ListMunicipiosPorZona,
			'region': region,
#			'EdicionEntidadForm': EdicionEntidadForm,
			'oficios': oficios,
		}
		return render(request,template_name, context)
#	def post(self, request, slug):
#		entidad = Entidad.objects.get(slug=slug)
#		EdicionEntidadForm = EntidadUpdateForm(instance=entidad, files=request.FILES, data=request.POST)

#		if EdicionEntidadForm.is_valid():
#			EdicionEntidadForm.save()
#			messages.success(request, "Actualización exitosa")

#		return redirect("accounts:ListViewZonas", slug=entidad.slug)

#Lista de escuelas
class ListViewEscuelas(View):
	@method_decorator(login_required)
	def get(self, request, pk=None):
		template_name = "accounts/listEscuelas.html"

		municipio = Municipio.objects.get(pk=pk)
		perfiles = Perfil.objects.filter(municipio=municipio)
		escuelas = User.objects.filter(perfil__in=perfiles).order_by('perfil__numero', 'perfil__localidad', 'perfil__nivel_educativo')
		zona = Zona.objects.get(municipio=municipio)
		entidad = Entidad.objects.get(zona=zona)
		municipio.CountEscuelas()

		context = {
			'municipio': municipio,
			'escuelas': escuelas,
			'entidad': entidad,
		}
		return render(request,template_name, context)

#Detalle de escuela
class DetailViewEscuela(View):
	@method_decorator(login_required)	
	def get(self, request, username):
		template_name = "accounts/detailEscuela.html"
		escuela = User.objects.get(username=username)
		perfil = Perfil.objects.get(user=escuela)
		perfil.UpdateEvidenciasCount()
		perfil.UpdateAvance()
		municipio = Municipio.objects.get(perfil=perfil)
		zona = Zona.objects.get(municipio=municipio)
		entidad = Entidad.objects.get(zona=zona)
		region = Region.objects.get(entidad=entidad)

		try: 
			perfilesRTs = Perfil.objects.filter(residente_tecnico_inifed=entidad)
			rts = User.objects.filter(perfil__in=perfilesRTs)

			perfilesROs = Perfil.objects.filter(residente_obra_ejecutora=entidad)
			ros = User.objects.filter(perfil__in=perfilesROs)

		except Perfil.DoesNotExist:
			perfilesRTs = None
			rts = None
			perfilesROs = None
			ros = None

		try:
			visitaDeAcuerdo = VisitaDeAcuerdo.objects.get(escuela=escuela)
		except VisitaDeAcuerdo.DoesNotExist:
			visitaDeAcuerdo = None

		try:
			primerPrueba = PrimerPrueba.objects.get(escuela=escuela)				
		except PrimerPrueba.DoesNotExist:
			primerPrueba = None

		try:
			sistemaBebedero = SistemaBebedero.objects.get(escuela=escuela)
		except SistemaBebedero.DoesNotExist:
			sistemaBebedero = None

		try:
			inicioDeTrabajo = InicioDeTrabajo.objects.get(escuela=escuela)
		except InicioDeTrabajo.DoesNotExist:
			inicioDeTrabajo = None

		try:
			evidenciasConstruccion = EvidenciaConstruccion.objects.filter(escuela=escuela)
			evidenciaFinal = evidenciasConstruccion.filter(fase="Instalación de Mueble Bebedero", aprobacion_SI = "Aprobado")
		except EvidenciaConstruccion.DoesNotExist:
			evidenciasConstruccion = None
			evidenciaFinal = None

		try:
			segundaPrueba = SegundaPrueba.objects.get(escuela=escuela)
		except SegundaPrueba.DoesNotExist:
			segundaPrueba = None

		try:
			funcionamiento = InicioFuncionamiento.objects.get(escuela=escuela)
		except InicioFuncionamiento.DoesNotExist:
			funcionamiento = None

		try:
			mantenimientos = Mantenimiento.objects.filter(escuela=escuela)
		except Mantenimiento.DoesNotExist:
			mantenimientos = None

		try: 
			actaEntrega = ActaEntrega.objects.get(escuela=escuela)
		except ActaEntrega.DoesNotExist:
			actaEntrega = None

		context = {
			'perfil': perfil,
			'escuela': escuela,
			'visitaDeAcuerdo': visitaDeAcuerdo,
			'sistemaBebedero': sistemaBebedero,
			'primerPrueba': primerPrueba,
			'inicioDeTrabajo': inicioDeTrabajo,
			'evidenciasConstruccion': evidenciasConstruccion,
			'evidenciaFinal': evidenciaFinal,
			'segundaPrueba': segundaPrueba,
			'funcionamiento': funcionamiento,
			'mantenimientos': mantenimientos,
			'actaEntrega': actaEntrega,
			'municipio': municipio,
			'zona': zona,
			'entidad': entidad,
			'region': region,
			'rts': rts,
			'ros': ros,
		}
		return render(request,template_name, context)

#Creación de escuela
class CreateViewEscuela(View):
	@method_decorator(login_required)
	def get(self, request, pk):
		template_name = "accounts/createEscuela.html"
		municipio = Municipio.objects.get(pk=pk)
		zona = Zona.objects.get(municipio=municipio)
		entidad = Entidad.objects.get(zona=zona)

		NuevaEscuelaUserForm = EscuelaUserCreateForm()
		NuevaEscuelaPerfilForm = EscuelaPerfilCreateForm()	
		NuevoBebederoForm = BebederoCreateForm()

		context = {
			'municipio': municipio,
			'NuevaEscuelaUserForm': NuevaEscuelaUserForm,
			'NuevaEscuelaPerfilForm': NuevaEscuelaPerfilForm,
			'NuevoBebederoForm': NuevoBebederoForm
		}
		return render(request,template_name, context)
	def post(self, request, pk):
		template_name = "accounts/createEscuela.html"		
		municipio = Municipio.objects.get(pk=pk)
		zona = Zona.objects.get(municipio=municipio)
		entidad = Entidad.objects.get(zona=zona)

		NuevaEscuelaUserForm = EscuelaUserCreateForm(request.POST)
		NuevaEscuelaPerfilForm = EscuelaPerfilCreateForm(request.POST)
		NuevoBebederoForm = BebederoCreateForm(request.POST)

		if NuevaEscuelaUserForm.is_valid() and NuevaEscuelaPerfilForm.is_valid() and NuevoBebederoForm.is_valid():
#		if NuevaEscuelaUserForm.is_valid():
			NuevaEscuelaUser = NuevaEscuelaUserForm.save(commit=False)
			NuevaEscuelaUser.set_password('generica')
			NuevaEscuelaUser.save()

#		if NuevaEscuelaPerfilForm.is_valid():
			NuevaEscuelaPerfil = NuevaEscuelaPerfilForm.save(commit=False)
			NuevaEscuelaPerfil.user = NuevaEscuelaUser
			NuevaEscuelaPerfil.tipo = "Escuela"
			NuevaEscuelaPerfil.municipio = municipio
			NuevaEscuelaPerfil.save()

#		if NuevoBebederoForm.is_valid():
			NuevoBebedero = NuevoBebederoForm.save(commit=False)
			NuevoBebedero.escuela = NuevaEscuelaUser
			NuevoBebedero.save()
			NuevoBebedero.CalculaCTP()
			municipio.CountEscuelas()
			entidad.CountEscuelas()
			
		else:
			context = {
				'municipio': municipio,
				'NuevaEscuelaUserForm': NuevaEscuelaUserForm,
				'NuevaEscuelaPerfilForm': NuevaEscuelaPerfilForm,
				'NuevoBebederoForm': NuevoBebederoForm				
			}
			return render(request,template_name,context)			
		return redirect("accounts:ListViewEscuelas", pk=municipio.pk)

#Actualización de escuela
class UpdateViewEscuela(View):
	@method_decorator(login_required)
	def get(self, request, username):
		template_name = "accounts/updateEscuela.html"
		#perfil = Perfil.objects.get(pk=pk)
		escuela = User.objects.get(username=username)
		perfil = Perfil.objects.get(user=escuela)

		EdicionEscuelaUserForm = EscuelaUserUpdateForm(instance=escuela)

accounts/templates/accounts/home.html
{%extends 'base.html'%}

{%load static%}
{%block content%}

<div class="row justify-content-center">
	<div class="col-7" style="padding-top: 50px;">
		<img src="{%static 'img/logomk.jpg'%}" style="width: 100%;">
	</div>
	<div class="col-7" style="padding-top: 50px;">
		<a href="{%url 'accounts:login'%}" class="btn btn-primary btn-lg" role="button" aria-pressed="true">Inicia sesión</a>
	</div>	
</div>
{%endblock content%}

accounts/templates/accounts/listZonas.html
{%extends 'base.html'%}

{%load bootstrap%}

{%block content%}

	<h1>{{entidad}}</h1>

		{%if request.user.perfil.cargo == "SIM" or request.user.perfil.tipo == "Laboratorio"%}

		<a href="{%url 'accounts:ListViewEntidades'%}">Regresar</a>

		{%elif request.user.perfil.tipo == "Administrador" or request.user.perfil.tipo == "PM" or request.user.perfil.tipo == "PQ" or request.user.perfil.cargo == "CRINIFED"  or  request.user.perfil.cargo == "EIINIFED" or  request.user.perfil.tipo == "Invitado"%}

		<a href="{%url 'accounts:ListViewEntidades' entidad.region.numero%}">Regresar</a>

		{%endif%}
	
	<h3>Información</h3>

	<div class="row justify-content-center">
		<div class="table-responsive">
			<table class="table table-bordered">

				<thead>
					<tr>
						<th rowspan="2">Región</th>
						<th rowspan="2">Partida</th>
						<th colspan="2">Escuelas</th>
					</tr>
					<tr>
						<th>Asignadas</th>
						<th>Registradas</th>
					</tr>
				</thead>
				<tbody>
					<tr>
					<td>{{entidad.region}}</td>
					<td>{{entidad.partida}}</td>
						<td>{{entidad.escuelas_asignadas}}</td>
						<td>{{entidad.escuelas_registradas}}</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>

	<h3>Municipios</h3>

	<div class="row justify-content-center">
		<div class="table-responsive text-center">
			<table class="table table-bordered">
				<thead>
					<tr>
						<th>Zona</th>
						<th>Nombre</th>
						<th>Escuelas registradas</th>
					</tr>
				</thead>
				<tbody>

					{%for MunicipiosPorZona in ListMunicipiosPorZona%}

						{%for municipio in MunicipiosPorZona.municipios%}

					<tr>

							{%if forloop.first%}
						
						<td rowspan=" {{MunicipiosPorZona.municipios|length}}" style="background-color:  {{MunicipiosPorZona.zona.color}};">{{MunicipiosPorZona.zona.nombre}}
						</td>

							{%endif%}

						<td><a href="{%url 'accounts:ListViewEscuelas' municipio.pk%}">{{municipio.nombre}}</a> 
						</td>
						<td>{{municipio.escuelas_registradas}}</td>						
						{%empty%}

							<td>{{MunicipiosPorZona.zona}}</td>
							<td colspan="5">No tiene municipios registrados</td>
						
						{%endfor%}
						
					</tr>

					{%empty%}

					<tr>
						<td colspan="6">No hay zonas registradas</td>
					</tr>

					{%endfor%}

				</tbody>
			</table>
		</div>
	</div>

	{%if request.user.perfil.tipo == "Administrador" or request.user.perfil.tipo == "PQ" or request.user.perfil.tipo == "Ejecutora" or request.user.perfil.tipo == "Laboratorio"  or request.user.perfil.tipo == "PM" or request.user.perfil.tipo == "Invitado"%}
	<div class="table-responsive espacio2">
		<table class="table table-bordered">
			<thead>
				<tr>
					<th colspan="5">Descarga masiva de documentos</th>
				</tr>
			</thead>
			<tbody>
				

				{%if request.user.perfil.tipo == "Ejecutora" or request.user.perfil.tipo == "Administrador"  or request.user.perfil.tipo == "PQ" or request.user.perfil.tipo == "Invitado"%}
				<tr>
					<td colspan="5">
						<a href="{%url 'accounts:ExportAvancePorEscuelasCSV' entidad.pk%}">Reporte general</a>
					</td>
				</tr>

				{%endif%}
				{%if request.user.perfil.tipo == "Administrador" or request.user.perfil.tipo == "Ejecutora" or request.user.perfil.tipo == "Invitado"%}

				<tr>
					<td>{%if entidad.t7%}<a href="{{entidad.t7.url}}">T7</a>{%else%}No se ha subido el archivo T7{%endif%}</td>
				</tr>
				{%endif%}
				<tr>
					{%if request.user.perfil.tipo == "PQ" or request.user.perfil.tipo == "Administrador" or  request.user.perfil.tipo == "Laboratorio" or request.user.perfil.tipo == "Invitado"%}
					<td colspan="5"><a href="{% url 'pruebas:ExportPruebasPorEscuelasCSV' entidad.pk%}">Base de formato T7</a>
					</td>
					{%endif%}
				</tr>
				<tr>
					{%if request.user.perfil.tipo == "PM" or request.user.perfil.tipo == "Administrador" or request.user.perfil.tipo == "Invitado"%}
					<td colspan="5"><a href="{% url 'bebederos:ExportAvanceBebederosCSV' entidad.pk%}">Avance de sistemas bebederos</a>
					</td>
					{%endif%}
				</tr>
				<tr>
					{%if request.user.perfil.tipo == "Administrador" or request.user.perfil.tipo == "Ejecutora" or request.user.perfil.tipo == "Invitado"%}
					<td colspan="5"><a href="{% url 'incidencias:ExportIncidenciasCSV' entidad.pk%}">Reporte de incidencias</a>
					</td>
					{%endif%}
				</tr>				
			</tbody>
		</table>
	</div>
	{%endif%}



	{%if request.user.perfil.tipo == "Administrador" or request.user.perfil.tipo == "Ejecutora"  or request.user.perfil.tipo == "INIFED" or request.user.perfil.tipo == "Invitado"%}
	<div class="table-responsive espacio2">
		<table class="table table-bordered">
			<thead>
				<tr>
					<th colspan="3">Oficios</th>
				</tr>
				<tr>
					<th>Nombre</th>
					<th>Fecha de subida</th>
					<th>Archivo</th>
				</tr>
			</thead>
			<tbody>
			{%for oficio in oficios%}
				<tr>
					<td>{{oficio.nombre}}
					</td>
					<td>
					{{oficio.fecha}}
					</td>
					<td><a href="{{oficio.archivo.url}}">Descargar</a>
					</td>

				</tr>
			{%endfor%}
			</tbody>
		</table>
	</div>
	{%endif%}	

{%endblock content%}