Bebederos/urls.py
from django.conf.urls import url, include
from django.contrib import admin

#urls of the apps
from accounts import urls as accountsUrls
from visitas import urls as visitasUrls
from construccion import urls as construccionUrls
from pruebasAgua import urls as pruebasAguaUrls
from incidencias import urls as incidenciasUrls
from mantenimiento import urls as mantenimientoUrls
from bebederos import urls as bebederosUrls
from plantillas import urls as plantillasUrls

#Media and static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^admin/', admin.site.urls),
    url(r'^', include(visitasUrls, namespace="visitas")),
    url(r'^', include(construccionUrls, namespace="construccion")),
    url(r'^', include(pruebasAguaUrls, namespace="pruebas")),
    url(r'^', include(incidenciasUrls, namespace="incidencias")),
    url(r'^', include(mantenimientoUrls, namespace="mantenimiento")),
    url(r'^', include(bebederosUrls, namespace="bebederos")),
    url(r'^', include(plantillasUrls, namespace="plantillas")),    
    url(r'^', include(accountsUrls, namespace="accounts")),
]

#Media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Static
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
	url(r'^login/$', login,name="login"),
	url(r'^logout/$', logout, name="logout"),
	url(r'^accounts/profile/$', views.ViewProfile.as_view(), name="ViewProfile"),
#	url(r'^accounts/nuevo/$', views.CreateViewAccount.as_view(), name="CreateViewAccount"),	
#	url(r'^change-password/$', views.ViewChangePassword.as_view(), name='ViewChangePassword'),

#	url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),
#	url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),
#	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),
#	url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),

	url(r'^expediente/export/zip/(?P<pk>\d+)/$', views.ExportExpedienteZIP, name='ExportExpedienteZIP'),
	url(r'^reporte_fotografico/export/zip/(?P<pk>\d+)/$', views.ExportFotosEvidenciaZIP, name='ExportFotosEvidenciaZIP'),
#	url(r'^region/estado/reporte_avance/zona/(?P<pk>[-\w]+)/$', views.ListViewAvanceEscuelas.as_view(), name="ListViewAvanceEscuelasPorZona"),

#	url(r'^region/estado/zona/$', views.ListViewZonas.as_view(), name="ListViewZonas2"),
#	url(r'^escuelas/por_ejecutora/$', views.ListViewEscuelas.as_view(), name="ListViewEscuelasPorEjecutora"),
#	url(r'^region/(?P<numero>[-\w]+)/estados/$', views.ListViewEntidades.as_view(), name="ListViewEntidades"),
	url(r'^escuelas/avance/export/csv/(?P<pk>\d+)/$', views.ExportAvancePorEscuelasCSV, name='ExportAvancePorEscuelasCSV'),
	url(r'^escuelas/search/$',views.SearchViewEscuelas.as_view(), name='SearchViewEscuelas'),
	url(r'^escuela/(?P<username>[-\w]+)/$', views.DetailViewEscuela.as_view(), name="DetailViewEscuela"),
	url(r'^escuela/mapa/(?P<pk>[-\w]+)/$', views.DetailViewMapa.as_view(), name="DetailViewMapa"),
	url(r'^escuela/actualizar/expediente/(?P<pk>[-\w]+)/$', views.UpdateViewEscuelaExpediente.as_view(), name="UpdateViewEscuelaExpediente"),
	url(r'^escuela/actualizar/(?P<username>[-\w]+)/$', views.UpdateViewEscuela.as_view(), name="UpdateViewEscuela"),
	url(r'^municipio/(?P<pk>[-\w]+)/escuela/crear/$', views.CreateViewEscuela.as_view(), name="CreateViewEscuela"),
	url(r'^municipio/(?P<pk>[-\w]+)/$', views.ListViewEscuelas.as_view(), name="ListViewEscuelas"),
	url(r'^estado/reporte_general/(?P<slug>[-\w]+)/$', views.ListViewAvanceEscuelas.as_view(), name="ListViewAvanceEscuelas"),
	url(r'^estado/(?P<slug>[-\w]+)/$', views.ListViewZonas.as_view(), name="ListViewZonas"),
	url(r'^estados/$', views.ListViewEntidades.as_view(), name="ListViewEntidades"),	
	url(r'^region/(?P<numero>[-\w]+)/$', views.ListViewEntidades.as_view(), name="ListViewEntidades"),
	url(r'^regiones/$', views.ListViewRegiones.as_view(), name="ListViewRegiones"),
	url(r'^$', views.ViewHome.as_view(), name="ViewHome"),
    ]

incidencias/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^incidencia/(?P<pk>\d+)/$', views.UpdateViewIncidencia.as_view(), name="UpdateViewIncidencia"),
	url(r'^incidencias/(?P<pk>\d+)/$', views.CRViewIncidencias.as_view(), name="CRViewIncidencias"),
	url(r'^incidencias/export/(?P<pk>\d+)/csv/$', views.ExportIncidenciasCSV, name='ExportIncidenciasCSV'),	
	url(r'^incidencias/$', views.CRViewIncidencias.as_view(), name="ListViewIncidencias"),
]

plantillas/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^plantillas/$', views.ListViewPlantillas.as_view(), name="ListViewPlantillas"),
]

visitas/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	#DescargasZip
	url(r'^cedulas_identificacion/export/zip/(?P<pk>\d+)/$', views.ExportCedulasIdentificacionZIP, name='ExportCedulasIdentificacionZIP'),
	url(r'^planos_conjunto/export/zip/(?P<pk>\d+)/$', views.ExportPlanosConjuntoZIP, name='ExportPlanosConjuntoZIP'),
	url(r'^distribucion_planta/export/zip/(?P<pk>\d+)/$', views.ExportDistribucionesPlantaZIP, name='ExportDistribucionesPlantaZIP'),
	url(r'^memoria_calculo/export/zip/(?P<pk>\d+)/$', views.ExportMemoriasCalculoZIP, name='ExportMemoriasCalculoZIP'),
	url(r'^plano_instalacion_electrica/export/zip/(?P<pk>\d+)/$', views.ExportPlanosInstalacionElectricaZIP, name='ExportPlanosInstalacionElectricaZIP'),
	url(r'^plano_instalacion_hidraulica/export/zip/(?P<pk>\d+)/$', views.ExportPlanosInstalacionHidraculicaZIP, name='ExportPlanosInstalacionHidraculicaZIP'),
	url(r'^plano_instalacion_sanitaria/export/zip/(?P<pk>\d+)/$', views.ExportPlanosInstalacionSanitariaZIP, name='ExportPlanosInstalacionSanitariaZIP'),
	url(r'^inicio_funcionamiento/export/zip/(?P<pk>\d+)/$', views.ExportActasFuncionamietoZIP, name='ExportActasFuncionamietoZIP'),

	url(r'^visita/de_acuerdo/(?P<pk>\d+)/$', views.CRViewVisitaDeAcuerdo.as_view(), name="CRViewVisitaDeAcuerdo"),
	url(r'^visita/entrega/(?P<pk>\d+)/$', views.CRViewInicioFuncionamiento.as_view(), name="CRViewInicioFuncionamiento"),
	url(r'^visita/acta_entrega/(?P<pk>\d+)/$', views.CRViewActaEntrega.as_view(), name="CRViewActaEntrega"),	
]

templates/base.html
{%load static%}
{%load my_tags%}

<html>
	<head>
		<title>TEASIB</title>
    <meta charset="utf-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		
    <link rel="stylesheet" type="text/css" href="{%static 'css/bootstrap.min.css'%}">

		<link rel="stylesheet" type="text/css" href="{%static 'css/font-awesome.min.css'%}">

    <link rel="stylesheet" type="text/css" href="{%static 'css/estilos.css'%}">
	</head>

	<body>

<nav class="navbar navbar-toggleable-md navbar-light bg-faded fixed-top" style="background-color: #44B036; border-bottom: solid 1px;">

{%if request.user.is_authenticated%}

  <button style="border-color: white;" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  {%endif%}
  <a class="navbar-brand" href="#" style="color: white;">TEASIB 1.21.5 Convocatoria {%anio_convocatoria%}</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
    </ul>
    {%if request.user.is_authenticated%}
    <ul class="navbar-nav mt-2 mt-md-0">
      <li class="nav-item">
        <a class="nav-link" href="{%url 'accounts:ViewProfile'%}"><i class="fa fa-home" aria-hidden="true"></i></a>
      </li>

      {%if request.user.perfil.tipo == "Escuela"%}

      <li class="nav-item">
        <a class="nav-link" href="{%url 'accounts:DetailViewEscuela' request.user.username%}">Expediente</a>
      </li>

      {%elif request.user.perfil.tipo == "Laboratorio"%}

      <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Escuelas
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{%url 'accounts:ListViewEntidades'%}">entidades</a>
                <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
              </div>
            </li>

      {%elif request.user.perfil.cargo == "SIM"%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewZonas' request.user.sim.slug%}">Municipios</a>
          <a class="dropdown-item" href="{%url 'accounts:ListViewAvanceEscuelas' request.user.sim.slug%}">Reporte general</a>          
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>      

      {%elif request.user.perfil.cargo == "SI"%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewZonas' request.user.superintendente.slug%}">Municipios</a>
          <a class="dropdown-item" href="{%url 'accounts:ListViewAvanceEscuelas' request.user.superintendente.slug%}">Reporte general</a>          
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>

      {%elif request.user.perfil.cargo == "RO"%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewZonas' request.user.perfil.residente_obra_ejecutora.slug%}">Municipios</a>
          <a class="dropdown-item" href="{%url 'accounts:ListViewAvanceEscuelas' request.user.perfil.residente_obra_ejecutora.slug%}">Reporte general</a>          
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>

      {%elif request.user.perfil.cargo == "CRINIFED"%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewEntidades' request.user.coordinador_regional_inifed.numero%}">Entidades</a>
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>

      {%elif request.user.perfil.cargo == "EIINIFED"%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewEntidades' request.user.enlace_institucional_inifed.numero%}">Entidades</a>
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>      

      {%elif request.user.perfil.cargo == "CEINIFED"%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewZonas' request.user.coordinador_estatal_inifed.slug%}">Municipios</a>
          <a class="dropdown-item" href="{%url 'accounts:ListViewAvanceEscuelas' request.user.coordinador_estatal_inifed.slug%}">Reporte general</a>          
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>

      {%elif request.user.perfil.cargo == "RTINIFED"%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewZonas' request.user.perfil.residente_tecnico_inifed.slug%}">Municipios</a>
          <a class="dropdown-item" href="{%url 'accounts:ListViewAvanceEscuelas' request.user.perfil.residente_tecnico_inifed.slug%}">Reporte general</a>          
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>

      {%elif request.user.perfil.tipo == "Administrador" or request.user.perfil.tipo == "PQ" or request.user.perfil.tipo == "PM" or request.user.perfil.tipo == "IMTA" or  request.user.perfil.tipo == "Invitado"%}

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewRegiones'%}">Regiones</a>
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>

      {%endif%}

      {%if request.user.perfil.tipo == "Administrador" or request.user.perfil.tipo == "PQ" or request.user.perfil.tipo == "PM" or request.user.perfil.tipo == "Ejecutora" or  request.user.perfil.tipo == "INIFED" or  request.user.perfil.tipo == "Invitado"%}

      <li class="nav-item">
        <a class="nav-link" href="{%url 'incidencias:ListViewIncidencias'%}">Incidencias</a>
      </li>

      {%endif%}
      <li class="nav-item">
        <a class="nav-link" href="{%url 'plantillas:ListViewPlantillas'%}">Plantillas</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'accounts:logout'%}">Cerrar sesión</a>
      </li>
    </ul>
     {%endif%}

  </div>
</nav>
  
	<div class="container content">

      {%block content%}
      {%endblock content%}
	
	</div>

        
        <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
        <script type="text/javascript" src="{%static 'js/jquery.js'%}"></script>
        <script type="text/javascript" src="{%static 'js/bootstrap.min.js'%}"></script>
        
	</body>
</html>

templates/base2.html
{%load static%}
<html>
	<head>
		<title>Seguimiento de bebederos</title>
    <meta charset="utf-8">
    
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		
    <link rel="stylesheet" type="text/css" href="{%static 'css/bootstrap.min.css'%}">

		<link rel="stylesheet" type="text/css" href="{%static 'css/font-awesome.min.css'%}">

    <link rel="stylesheet" type="text/css" href="{%static 'css/estilos2.css'%}">
	</head>

  </style>
	<body>

<nav class="navbar navbar-toggleable-md navbar-light bg-faded fixed-top" style="background-color: #0000EE; border-bottom: solid 1px;">

{%if request.user.is_authenticated%}

  <button style="border-color: white;" class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  {%endif%}
  <a class="navbar-brand" href="#" style="color: white;">Seguimiento de Bebederos</a>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-md-0">
    </ul>
    {%if request.user.is_authenticated%}
    <ul class="navbar-nav mt-2 mt-md-0">
      <li class="nav-item">
        <a class="nav-link" href="{%url 'accounts:ViewProfile'%}"><i class="fa fa-home" aria-hidden="true"></i></a>
      </li>

      {%if request.user.perfil.tipo == "Escuela"%}

      <li class="nav-item">
        <a class="nav-link" href="{%url 'accounts:DetailViewEscuela' request.user.username%}">Expediente</a>
      </li>

      {%elif request.user.perfil.tipo == "Laboratorio"%}

      <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Escuelas
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a class="dropdown-item" href="{%url 'accounts:ListViewEntidades'%}">Por entidades</a>
                <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
              </div>
            </li>

      {%elif request.user.perfil.cargo == "SIM"%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewZonas' request.user.sim.slug%}">Por municipios</a>
          <a class="dropdown-item" href="{%url 'accounts:ListViewAvanceEscuelas' request.user.sim.slug%}">Reporte general</a>          
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>      

      {%elif request.user.perfil.cargo == "SI"%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewZonas' request.user.superintendente.slug%}">Por municipios</a>
          <a class="dropdown-item" href="{%url 'accounts:ListViewAvanceEscuelas' request.user.superintendente.slug%}">Reporte general</a>          
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>

      {%elif request.user.perfil.cargo == "RO"%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewZonas' request.user.perfil.residente_obra_ejecutora.slug%}">Por municipios</a>
          <a class="dropdown-item" href="{%url 'accounts:ListViewAvanceEscuelas' request.user.perfil.residente_obra_ejecutora.slug%}">Reporte general</a>          
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>

      {%elif request.user.perfil.cargo == "CRINIFED"%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewEntidades' request.user.coordinador_regional_inifed.numero%}">Entidades</a>
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>

      {%elif request.user.perfil.cargo == "EIINIFED"%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewEntidades' request.user.enlace_institucional_inifed.numero%}">Entidades</a>
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>      

      {%elif request.user.perfil.cargo == "CEINIFED"%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewZonas' request.user.coordinador_estatal_inifed.slug%}">Por municipios</a>
          <a class="dropdown-item" href="{%url 'accounts:ListViewAvanceEscuelas' request.user.coordinador_estatal_inifed.slug%}">Reporte general</a>          
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>

      {%elif request.user.perfil.cargo == "RTINIFED"%}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewZonas' request.user.perfil.residente_tecnico_inifed.slug%}">Por municipios</a>
          <a class="dropdown-item" href="{%url 'accounts:ListViewAvanceEscuelas' request.user.perfil.residente_tecnico_inifed.slug%}">Reporte general</a>          
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>

      {%elif request.user.perfil.tipo == "Administrador" or request.user.perfil.tipo == "PQ" or request.user.perfil.tipo == "PM" or request.user.perfil.tipo == "IMTA" or  request.user.perfil.tipo == "Invitado"%}

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Escuelas</a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{%url 'accounts:ListViewRegiones'%}">Por regiones</a>
          <a class="dropdown-item" href="{%url 'accounts:SearchViewEscuelas'%}">Buscar</a>
        </div>
      </li>

      {%endif%}

      {%if request.user.perfil.tipo == "Administrador" or request.user.perfil.tipo == "PQ" or request.user.perfil.tipo == "PM" or request.user.perfil.tipo == "Ejecutora" or  request.user.perfil.tipo == "INIFED" or  request.user.perfil.tipo == "Invitado"%}

      <li class="nav-item">
        <a class="nav-link" href="{%url 'incidencias:ListViewIncidencias'%}">Incidencias</a>
      </li>

      {%endif%}
      <li class="nav-item">
        <a class="nav-link" href="{%url 'plantillas:ListViewPlantillas'%}">Plantillas</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'accounts:logout'%}">Cerrar sesión</a>
      </li>
    </ul>
     {%endif%}

  </div>
</nav>
<div style="padding: 0; margin: 0;">
      {%block content%}
      {%endblock content%}
</div>	
        
        <script src="https://npmcdn.com/tether@1.2.4/dist/js/tether.min.js"></script>
        <script type="text/javascript" src="{%static 'js/jquery.js'%}"></script>
        <script type="text/javascript" src="{%static 'js/bootstrap.min.js'%}"></script>
        
	</body>
</html>