Bebederos/urls.py
from django.conf.urls import url, include
from django.contrib import admin

#urls of the apps
from accounts import urls as accountsUrls
from visitas import urls as visitasUrls
from construccion import urls as construccionUrls
from pruebasAgua import urls as pruebasAguaUrls
from incidencias import urls as incidenciasUrls
from mantenimiento import urls as mantenimientoUrls
from bebederos import urls as bebederosUrls
from plantillas import urls as plantillasUrls

#Media and static
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^admin/', admin.site.urls),
    url(r'^', include(visitasUrls, namespace="visitas")),
    url(r'^', include(construccionUrls, namespace="construccion")),
    url(r'^', include(pruebasAguaUrls, namespace="pruebas")),
    url(r'^', include(incidenciasUrls, namespace="incidencias")),
    url(r'^', include(mantenimientoUrls, namespace="mantenimiento")),
    url(r'^', include(bebederosUrls, namespace="bebederos")),
    url(r'^', include(plantillasUrls, namespace="plantillas")),    
    url(r'^', include(accountsUrls, namespace="accounts")),
]

#Media
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#Static
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done, password_reset_confirm, password_reset_complete

urlpatterns = [
	url(r'^login/$', login,name="login"),
	url(r'^logout/$', logout, name="logout"),
	url(r'^accounts/profile/$', views.ViewProfile.as_view(), name="ViewProfile"),
#	url(r'^accounts/nuevo/$', views.CreateViewAccount.as_view(), name="CreateViewAccount"),	
#	url(r'^change-password/$', views.ViewChangePassword.as_view(), name='ViewChangePassword'),

#	url(r'^reset-password/$', password_reset, {'template_name': 'accounts/reset_password.html', 'post_reset_redirect': 'accounts:password_reset_done', 'email_template_name': 'accounts/reset_password_email.html'}, name='reset_password'),
#	url(r'^reset-password/done/$', password_reset_done, {'template_name': 'accounts/reset_password_done.html'}, name='password_reset_done'),
#	url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', password_reset_confirm, {'template_name': 'accounts/reset_password_confirm.html', 'post_reset_redirect': 'accounts:password_reset_complete'}, name='password_reset_confirm'),
#	url(r'^reset-password/complete/$', password_reset_complete,{'template_name': 'accounts/reset_password_complete.html'}, name='password_reset_complete'),

	url(r'^expediente/export/zip/(?P<pk>\d+)/$', views.ExportExpedienteZIP, name='ExportExpedienteZIP'),
	url(r'^reporte_fotografico/export/zip/(?P<pk>\d+)/$', views.ExportFotosEvidenciaZIP, name='ExportFotosEvidenciaZIP'),
#	url(r'^region/estado/reporte_avance/zona/(?P<pk>[-\w]+)/$', views.ListViewAvanceEscuelas.as_view(), name="ListViewAvanceEscuelasPorZona"),

#	url(r'^region/estado/zona/$', views.ListViewZonas.as_view(), name="ListViewZonas2"),
#	url(r'^escuelas/por_ejecutora/$', views.ListViewEscuelas.as_view(), name="ListViewEscuelasPorEjecutora"),
#	url(r'^region/(?P<numero>[-\w]+)/estados/$', views.ListViewEntidades.as_view(), name="ListViewEntidades"),
	url(r'^escuelas/avance/export/csv/(?P<pk>\d+)/$', views.ExportAvancePorEscuelasCSV, name='ExportAvancePorEscuelasCSV'),
	url(r'^escuelas/search/$',views.SearchViewEscuelas.as_view(), name='SearchViewEscuelas'),
	url(r'^escuela/(?P<username>[-\w]+)/$', views.DetailViewEscuela.as_view(), name="DetailViewEscuela"),
	url(r'^escuela/mapa/(?P<pk>[-\w]+)/$', views.DetailViewMapa.as_view(), name="DetailViewMapa"),
	url(r'^escuela/actualizar/expediente/(?P<pk>[-\w]+)/$', views.UpdateViewEscuelaExpediente.as_view(), name="UpdateViewEscuelaExpediente"),
	url(r'^escuela/actualizar/(?P<username>[-\w]+)/$', views.UpdateViewEscuela.as_view(), name="UpdateViewEscuela"),
	url(r'^municipio/(?P<pk>[-\w]+)/escuela/crear/$', views.CreateViewEscuela.as_view(), name="CreateViewEscuela"),
	url(r'^municipio/(?P<pk>[-\w]+)/$', views.ListViewEscuelas.as_view(), name="ListViewEscuelas"),
	url(r'^estado/reporte_general/(?P<slug>[-\w]+)/$', views.ListViewAvanceEscuelas.as_view(), name="ListViewAvanceEscuelas"),
	url(r'^estado/(?P<slug>[-\w]+)/$', views.ListViewZonas.as_view(), name="ListViewZonas"),
	url(r'^estados/$', views.ListViewEntidades.as_view(), name="ListViewEntidades"),	
	url(r'^region/(?P<numero>[-\w]+)/$', views.ListViewEntidades.as_view(), name="ListViewEntidades"),
	url(r'^regiones/$', views.ListViewRegiones.as_view(), name="ListViewRegiones"),
	url(r'^$', views.ViewHome.as_view(), name="ViewHome"),
    ]

construccion/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [

	url(r'^construccion/inicio_de_trabajo/(?P<pk>\d+)/$', views.CRViewInicioDeTrabajo.as_view(), name="CRViewInicioDeTrabajo"),
	url(r'^construccion/termino_de_trabajo/(?P<pk>\d+)/$', views.CRViewTerminoDeTrabajo.as_view(), name="CRViewTerminoDeTrabajo"),
	url(r'^construccion/evidencia/update/(?P<pk>\d+)/$', views.UpdateViewEvidencia.as_view(), name="UpdateViewEvidencia"),
	url(r'^construccion/evidencias/(?P<pk>\d+)/$', views.CRViewEvidencias.as_view(), name="CRViewEvidencias"),
]

visitas/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
	#DescargasZip
	url(r'^cedulas_identificacion/export/zip/(?P<pk>\d+)/$', views.ExportCedulasIdentificacionZIP, name='ExportCedulasIdentificacionZIP'),
	url(r'^planos_conjunto/export/zip/(?P<pk>\d+)/$', views.ExportPlanosConjuntoZIP, name='ExportPlanosConjuntoZIP'),
	url(r'^distribucion_planta/export/zip/(?P<pk>\d+)/$', views.ExportDistribucionesPlantaZIP, name='ExportDistribucionesPlantaZIP'),
	url(r'^memoria_calculo/export/zip/(?P<pk>\d+)/$', views.ExportMemoriasCalculoZIP, name='ExportMemoriasCalculoZIP'),
	url(r'^plano_instalacion_electrica/export/zip/(?P<pk>\d+)/$', views.ExportPlanosInstalacionElectricaZIP, name='ExportPlanosInstalacionElectricaZIP'),
	url(r'^plano_instalacion_hidraulica/export/zip/(?P<pk>\d+)/$', views.ExportPlanosInstalacionHidraculicaZIP, name='ExportPlanosInstalacionHidraculicaZIP'),
	url(r'^plano_instalacion_sanitaria/export/zip/(?P<pk>\d+)/$', views.ExportPlanosInstalacionSanitariaZIP, name='ExportPlanosInstalacionSanitariaZIP'),
	url(r'^inicio_funcionamiento/export/zip/(?P<pk>\d+)/$', views.ExportActasFuncionamietoZIP, name='ExportActasFuncionamietoZIP'),

	url(r'^visita/de_acuerdo/(?P<pk>\d+)/$', views.CRViewVisitaDeAcuerdo.as_view(), name="CRViewVisitaDeAcuerdo"),
	url(r'^visita/entrega/(?P<pk>\d+)/$', views.CRViewInicioFuncionamiento.as_view(), name="CRViewInicioFuncionamiento"),
	url(r'^visita/acta_entrega/(?P<pk>\d+)/$', views.CRViewActaEntrega.as_view(), name="CRViewActaEntrega"),	
]

construccion/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

class InicioDeTrabajo(models.Model):
	escuela = models.OneToOneField(User, related_name="escuela_inicio_trabajo")
	acta_inicio = models.FileField(upload_to='iniciosTrabajo/actas/%Y/%m/%d/', verbose_name="Acta de inicio de construcción")

	def __str__(self):
		return '{}'.format(self.escuela)

	class Meta:
		ordering = ['escuela']
		verbose_name_plural = 'Inicio de trabajos'

class EnvolventeTerminada(models.Model):
	escuela = models.OneToOneField(User, related_name="escuela_instalacion_bebedero")
	video = models.FileField(upload_to='evidencia/envolvente/%Y/%m/%d/', verbose_name="Video")

	def __str__(self):
		return '{}'.format(self.escuela)

	class Meta:
		ordering = ['escuela']
		verbose_name_plural = 'Envolventes terminadas'

class EvidenciaConstruccion(models.Model):
	fase_choices = (
		("1° Trazo", "1° Trazo"),
		("2° Excavación, corte y demolición", "2° Excavación, corte y demolición"),
		("3° Cimbra y habilitado de firme", "3° Cimbra y habilitado de firme"),
		("4° Colado de firme", "4° Colado de firme"),
		("5° Muros, castillos y cadenas" , "5° Muros, castillos y cadenas"),
		("6° Aplanados, pinturas y rampa", "6° Aplanados, pinturas y rampa"),
		("7° Estructura y puerta", "7° Estructura y puerta"),
		("8° Policarbonato", "8° Policarbonato"),
		("9° Mueble bebedero", "9° Mueble bebedero"),
		("10° Placa de identidad", "10° Placa de identidad"),
	)

	aprobacion_choices = (
		("En espera", "En espera"),
		("Aprobado", "Aprobado"),
		("No aprobado", "No aprobado"),
	)

	escuela = models.ForeignKey(User, related_name="escuela_evidencia")
	fase = models.CharField(max_length=50, choices=fase_choices)
	foto = models.FileField(upload_to='evidencia/foto/%Y/%m/%d/', verbose_name="Fotografía")
	aprobacion_SI = models.CharField(max_length=11, default="En espera", choices=aprobacion_choices, verbose_name="Aprobación del Superintendente")
	creacion = models.DateTimeField(default=timezone.now, verbose_name="Fecha de creación")

	def __str__(self):
		return 'Fase {} de {}'.format(self.fase, self.escuela)

	class Meta:
		ordering = ['escuela']
		verbose_name_plural = 'Evidencias de construcción'

construccion/forms.py
from django import forms
from .models import *

class InicioDeTrabajoCreateForm(forms.ModelForm):
	class Meta:
		model = InicioDeTrabajo
		fields = ('acta_inicio',)

class EnvolventeTerminadaCreateForm(forms.ModelForm):
	class Meta:
		model = EnvolventeTerminada
		fields = ('video',)
#		fields = ()

class EvidenciaConstruccionCreateForm(forms.ModelForm):
	class Meta:
		model = EvidenciaConstruccion
		fields = ('fase', 'foto')

class EvidenciaConstruccionEditForm(forms.ModelForm):
	class Meta:
		model = EvidenciaConstruccion
		fields = ('aprobacion_SI',)

construccion/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import View
from accounts.models import Perfil
from django.contrib.auth.models import User
from .forms import *
from django.contrib import messages
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required

#Creación, edición y detalle de una visita de acuerdo
class CRViewInicioDeTrabajo(View):
	@method_decorator(login_required)
	def get(self, request, pk):
		template_name = "construccion/CRInicioDeTrabajo.html"
		perfil = get_object_or_404(Perfil, pk=pk)
		escuela = User.objects.get(perfil=perfil)
		NuevoInicioForm = InicioDeTrabajoCreateForm()

		try:
			inicio = InicioDeTrabajo.objects.get(escuela=escuela)
			EdicionInicioForm = InicioDeTrabajoCreateForm(instance=inicio)
		except InicioDeTrabajo.DoesNotExist:
			inicio = None
			EdicionInicioForm = None

		context = {
			'perfil': perfil,
			'escuela': escuela,
			'NuevoInicioForm': NuevoInicioForm,
			'inicio': inicio,
			'EdicionInicioForm': EdicionInicioForm,
		}
		return render(request, template_name, context)
	def post(self, request, pk):
		perfil = get_object_or_404(Perfil, pk=pk)
		escuela = User.objects.get(perfil=perfil)
		NuevoInicioForm = InicioDeTrabajoCreateForm(data=request.POST, files=request.FILES)
		si = User.objects.get(pk=request.user.pk)

		try:
			inicio = InicioDeTrabajo.objects.get(escuela=escuela)
			EdicionInicioForm = InicioDeTrabajoCreateForm(instance=inicio, files=request.FILES)

			if EdicionInicioForm.is_valid():
				EdicionInicioForm.save()

		except InicioDeTrabajo.DoesNotExist:
			inicio = None
			EdicionInicioForm = None

			if NuevoInicioForm.is_valid():
				NuevoInicio = NuevoInicioForm.save(commit=False)
				NuevoInicio.escuela = escuela
				NuevoInicio.si = si
				NuevoInicio.save()

		return redirect("construccion:CRViewInicioDeTrabajo", pk=perfil.pk)

#Creación, edición y detalle de un termino de trabajos
class CRViewTerminoDeTrabajo(View):
	@method_decorator(login_required)
	def get(self, request, pk):
		template_name = "construccion/CRTerminoDeTrabajo.html"
		perfil = get_object_or_404(Perfil, pk=pk)
		escuela = User.objects.get(perfil=perfil)
		NuevoTerminoForm = TerminoDeTrabajoCreateForm()

		try:
			termino = TerminoDeTrabajo.objects.get(escuela=escuela)
		except TerminoDeTrabajo.DoesNotExist:
			termino = None

		context = {
			'perfil': perfil,
			'escuela': escuela,
			'NuevoTerminoForm': NuevoTerminoForm,
			'termino': termino,
		}
		return render(request, template_name, context)
	def post(self, request, pk):
		perfil = get_object_or_404(Perfil, pk=pk)
		escuela = User.objects.get(perfil=perfil)
		NuevoTerminoForm = TerminoDeTrabajoCreateForm(data=request.POST, files=request.FILES)
		si = User.objects.get(pk=request.user.pk)

		if NuevoTerminoForm.is_valid():
			NuevoTermino = NuevoTerminoForm.save(commit=False)
			NuevoTermino.escuela = escuela
			NuevoTermino.si = si
			NuevoTermino.save()

		return redirect("construccion:ViewTerminoDeTrabajo", pk=perfil.pk)

#Creación, edición y lista de evidencias de construcción 
class CRViewEvidencias(View):
	@method_decorator(login_required)
	def get(self, request, pk):
		template_name = "construccion/CREvidencias.html"
		perfil = get_object_or_404(Perfil, pk=pk)
		perfil.UpdateEvidenciasCount()
		perfil.UpdateAvance()

		escuela = User.objects.get(perfil=perfil)

		evidencias = EvidenciaConstruccion.objects.filter(escuela=escuela).order_by("fase")
#		evidencias = evidencias.extra(select={'myinteger': 'CAST(fase AS INTEGER)'}).order_by('myinteger')
#		print(e2) 

		NuevaEvidenciaForm = EvidenciaConstruccionCreateForm()
		NuevaEnvolventeForm = EnvolventeTerminadaCreateForm()
		
		try:
			envolvente = EnvolventeTerminada.objects.get(escuela=escuela)
		except EnvolventeTerminada.DoesNotExist:
			envolvente = None

		context = {
			'perfil': perfil,
			'escuela': escuela,
			'evidencias': evidencias,
			'NuevaEvidenciaForm': NuevaEvidenciaForm,
			'NuevaEnvolventeForm': NuevaEnvolventeForm,
			'envolvente': envolvente,
		}
		return render(request, template_name, context)
	def post(self, request, pk):
		perfil = get_object_or_404(Perfil, pk=pk)
		escuela = User.objects.get(perfil=perfil)

		NuevaEvidenciaForm = EvidenciaConstruccionCreateForm(data=request.POST, files=request.FILES)
		
		if NuevaEvidenciaForm.is_valid():
			NuevaEvidencia = NuevaEvidenciaForm.save(commit=False)
			NuevaEvidencia.escuela = escuela
			NuevaEvidencia.save()
			messages.success(request, "Actualización exitosa")			
			perfil.UpdateEvidenciasCount()
			
		NuevaEnvolventeForm = EnvolventeTerminadaCreateForm(data=request.POST, files=request.FILES)
		si = User.objects.get(pk=request.user.pk)

		if NuevaEnvolventeForm.is_valid():
			NuevaEnvolvente = NuevaEnvolventeForm.save(commit=False)
			NuevaEnvolvente.escuela = escuela
			NuevaEnvolvente.si = si
			NuevaEnvolvente.save()
			messages.success(request, "Actualización exitosa")

		return redirect("construccion:CRViewEvidencias", pk=perfil.pk)

#Actualización de una evidencia
class UpdateViewEvidencia(View):
	@method_decorator(login_required)
	def get(self, request, pk):
		template_name = "construccion/updateEvidencia.html"
		evidencia = get_object_or_404(EvidenciaConstruccion, pk=pk)
		EdicionEvidenciaForm = EvidenciaConstruccionCreateForm(instance=evidencia)
		EdicionEvidenciaForm2 = EvidenciaConstruccionEditForm(instance=evidencia)
		escuela = User.objects.get(escuela_evidencia=evidencia)
		perfil = Perfil.objects.get(user_id=escuela)

		context = {
			'evidencia': evidencia,
			'EdicionEvidenciaForm': EdicionEvidenciaForm,
			'EdicionEvidenciaForm2': EdicionEvidenciaForm2,	
			'escuela': escuela,
			'perfil': perfil,
		}
		return render(request, template_name, context)
	def post(self, request, pk):
		evidencia = get_object_or_404(EvidenciaConstruccion, pk=pk)

		escuela = User.objects.get(escuela_evidencia=evidencia)
		perfil = Perfil.objects.get(user_id=escuela)
		
		EdicionEvidenciaForm=EvidenciaConstruccionCreateForm(instance=evidencia, data=request.POST, files=request.FILES)
		if EdicionEvidenciaForm.is_valid():
			EdicionEvidenciaForm.save()

		EdicionEvidenciaForm2=EvidenciaConstruccionEditForm(instance=evidencia, data=request.POST, files=request.FILES)
		if EdicionEvidenciaForm2.is_valid():
			EdicionEvidenciaForm2.save()
			perfil.UpdateAvance()

		return redirect("construccion:CRViewEvidencias", pk=perfil.pk)

construccion/templates/construccion/CREvidencias.html
{%extends 'base.html'%}

{%load bootstrap%}

{%block content%}


	<div class="row">
		<div class="col-12">

		{% for message in messages %}
	
			<div class="alert alert-{{ message.tags }}">{{ message }}</div>

		{% endfor %}
		
			<h1>Evidencias de construcción e instalación de sistema bebedero (6-10 fotos)</h1>
			<a href="{%url 'accounts:DetailViewEscuela' perfil.user.username%}">Regresar</a>
			<h3>Escuela {{escuela.get_full_name}}</h3>
		</div>
	</div>

	<div class="row">
		<div class="col-12">

	{%if request.user.perfil.tipo == "Administrador"%}
		{%if evidencias.count < 10%}
			<form action="." method="post" enctype="multipart/form-data">
				<h4>Registro de evidencia de construcción</h4>	
				{%csrf_token%}
				{{NuevaEvidenciaForm | bootstrap}}
				<a href=""><input type="submit" value="Registrar"></a>
			</form>
		{%endif%}
	{%endif%}
			<h4>Evidencias de construcción</h4>
			<div class="table-responsive">
				<table class="table table-bordered">
					<thead>

					{%if not request.user.perfil.tipo == "INIFED"%}

						<th>Folio</th>

					{%endif%}
						<th>Fase</th>

					{%if not request.user.perfil.tipo == "INIFED"%}
						
						<th>Hora y fecha de registro</th>	
						<th>Aprobación de SIM</th>

						{%endif%}	
						<th colspan="{%if not request.user.perfil.tipo == "INIFED"%}2{%else%}1{%endif%}">Opciones</th>
					</thead>
					<tbody>
					
					{% for evidencia in evidencias%}

						<tr>
						{%if not request.user.perfil.tipo == "INIFED"%}

							<td>{{evidencia.pk}}</td>
						
						{%endif%}

							<td>{{evidencia.fase}}</td>
						
						{%if not request.user.perfil.tipo == "INIFED"%}
							<td>{{evidencia.creacion}}</td>
						{%endif%}
						{%if not request.user.perfil.tipo == "INIFED"%}

							<td>{{evidencia.aprobacion_SI}}</td>
						
						{%endif%}	
							<td><a href="{{evidencia.foto.url}}">Ver</a></td>

							{%if request.user.perfil.tipo == "Administrador"%}

							<td><a href="{%url 'construccion:UpdateViewEvidencia' evidencia.pk%}">{%if request.user.perfil.tipo == "Administrador"%}Revisar{%else%}Editar{%endif%}</a></td>
							{%endif%}
						</tr>

					{%empty%}

						<tr>
							<td colspan="5">Sin registro</td>
						</tr>

					{%endfor%}

					</tbody>
				</table>
			</div>


		</div>
	</div>

	{%if evidencias.count == 10%}
		{%if envolvente%}

	<div class="row">
		<div class="col-12">
			<h4>Envolvente terminada</h4>
		</div>
	</div>
	
	<div class="row justify-content-center ">
		<div class="col-md-5">

			<a href="{{envolvente.video.url}}" class="btn btn-primary btn-lg" role="button" aria-pressed="true">Video</a>
		</div>
	</div>

		{%else%}

	<div class="row">
		<div class="col-12">
			<form action="." method="post" enctype="multipart/form-data">
			<h4>Registro de video de envolvente terminada</h4>
			{%csrf_token%}
			{{NuevaEnvolventeForm | bootstrap}}
			<a href=""><input type="submit" value="Crear registro"></a>
			</form>
		</div>
	</div>

		{%endif%}
	{%endif%}
	
{%endblock content%}

construccion/templates/construccion/CRInicioDeTrabajo.html
{%extends 'base.html'%}

{% load bootstrap %}

{%block content%}

	<div class="row">
		<div class="col-12">	
			<h1>Inicio de Construcción</h1>
			<a href="{%url 'accounts:DetailViewEscuela' perfil.user.username%}">Regresar</a>
			<h3>Escuela {{escuela.get_full_name}}</h3>
		</div>
	</div>

	{%if inicio%}

	<div class="row">
		<div class="col-12">
			<h4>Consulta de documentación</h4>
		</div>
	</div>

	<div class="row justify-content-center text-center">
		<div class="col-md-5">

	{%if inicio.acta_inicio%}

			<a href="{{inicio.acta_inicio.url}}" class="btn btn-primary btn-lg" role="button" aria-pressed="true">Acta de inicio de contrucción</a>
	
	{%endif%}

		</div>
	</div>

	{%if request.user.perfil.tipo == "Administrador" or request.user.perfil.tipo == "INIFED"%}
	<div class="row">
		<div class="col-12">
			<form action="." method="post" enctype="multipart/form-data">
				<h4>Actualización de documentación</h4>
				{%csrf_token%}
				{{EdicionInicioForm | bootstrap}}
				<a href=""><input type="submit" value="Crear registro"></a>
			</form>
		</div>
	</div>
	{%endif%}

	{%else%}
	
	{%if request.user.perfil.tipo == "Administrador" or request.user.perfil.tipo == "INIFED"%}
	<div class="row">
		<div class="col-12">
			<form action="." method="post" enctype="multipart/form-data">
				<h4>Registro de documentación</h4>
				{%csrf_token%}
				{{NuevoInicioForm | bootstrap}}
				<a href=""><input type="submit" value="Crear registro"></a>
			</form>
		</div>
	</div>
	{%endif%}
	{%endif%}

{%endblock content%}

construccion/templates/construccion/createInicioDeTrabajo.html
{%extends 'base.html'%}

{% load bootstrap %}

{%block content%}

	<div class="row">
		<div class="col-12">	
			<h1>Inicio de trabajo</h1>
			<a href="{%url 'accounts:DetailViewEscuela' perfil.pk%}">Regresar</a>
			<h3>Escuela {{perfil.nivel_educativo}} "{{escuela.get_full_name}}"</h3>
		</div>
	</div>

	{%if inicio%}

	<div class="row">
		<div class="col-12">
			<h4>Consulta de documentación</h4>
		</div>
	</div>

	<div class="row justify-content-center text-center">
		<div class="col-md-5">

	{%if inicio.acta_inicio%}

			<a href="{{inicio.acta_inicio.url}}" class="btn btn-primary btn-lg" role="button" aria-pressed="true">Acta de inicio de trabajos</a>

	{%else%}
		
		<p>Pendiente a subir</p>
	
	{%endif%}

		</div>
	</div>

	{%else%}
	
	<div class="row">
		<div class="col-12">
			<form action="." method="post" enctype="multipart/form-data">
				<h4>Registro de documentación</h4>
				{%csrf_token%}
				{{NuevoInicioForm | bootstrap}}
				<a href=""><input type="submit" value="Crear registro"></a>
			</form>
		</div>
	</div>

	{%endif%}

{%endblock content%}

construccion/templates/construccion/updateEvidencia.html
{%extends 'base.html'%}

{%load bootstrap%}

{%block content%}
	<div class="row">
		<div class="col-12">
			<h1>Evidencia de la escuela {{escuela.username}} {{evidencia.escuela.get_full_name}}</h1>
			<a href="{%url 'construccion:CRViewEvidencias' evidencia.escuela.perfil.pk%}">Regresar</a>

			<form action="." method="post" enctype="multipart/form-data">
				{%csrf_token%}
				{{EdicionEvidenciaForm | bootstrap}}
				<p>Fotografía: <a href="{{evidencia.foto.url}}">Ver</a></p>
				<p>Creación: {{evidencia.creacion}}</p>	
				{%if request.user.perfil.cargo == "SIM" or request.user.perfil.tipo == "Administrador"%}	
				{{EdicionEvidenciaForm2 | bootstrap}}
				{%endif%}
				<a href=""><input type="submit" value="Guardar cambios"></a>		
			</form>
		</div>
	</div>

{%endblock content%}